### PR TITLE
Apply yapf formatting

### PR DESCRIPTION
**Pull request by rakhimov**
Fix all the formatting issues in one go with yapf.

### CODE REVIEW

**Comment by rakhimov** [comment]
CODACY_PROJECT_TOKEN private env var is not available for PR builds on Travis CI.
Coveralls or codecov are better alternatives to Codacy for code coverage reports
that do integrate well with PRs (no need for secret keys).

**Comment by weibullguy** [comment]
Many (as in dozens) of the files that were re-formtted in the PR will be removed from the repo as the API is updated for each module so I am closing this PR without merging.

Every file gets the following chain applied as it is being worked and before it is commited:

    yapf --> pylint --> pycodestyle --> pydocstyle

I have this in a script so I can run it from my IDE at the press of a button.  I've added my StaticChecks.sh script in tools directory to the repo for others to use if desired.

I had installed coveralls several weeks ago and forgot to integrate it!  It's integrated now, but keep in mind many (dozens) of the files in the repo will be eliminated, so I'm not that concerned with their coverage at the moment.  Only the RTK modules that have been refactored are of concern (currently Revision, Function, Requirements, Stakeholders, Usage, and Validation).

**Comment by rakhimov** [comment]
This simple one-commit batch processing (yapf, pylint, etc.) would've saved everybody time.
That some (dozens out of 440) will be deleted in future is irrelevant.
More importantly, you have to be careful to keep commits atomic and
not to mix formatting and code changes in the same commit.

**Comment by weibullguy** [comment]
You make a fair point; re-opened.

**Pull request merged**
