### PR TITLE
Fix pylint 'trailing whitespace' warnings

### PR DESCRIPTION
**Pull request by rakhimov**
Most trailing whitespace seems to be in license boilerplate.

### CODE REVIEW

**Comment by weibullguy** [comment]
I'm actually removing the license boilerplate text from each of the source files as I work on them.  It's not needed in each file and simply clutters them up.

**Comment by rakhimov** [comment]
Yea, it is clutter; thankfully my editor folds/hide them by default.
I am not a lawyer, but most FOSS projects keep license or at-least ``Copyright (C) years Name`` per file.

Do you want me to close this PR?

**Comment by weibullguy** [comment]
You'll note the 6th line in each file contains (or should contain) the copyright statement.  You can keep this open, I'll merge it in case any of the Windows file endings are laying around elsewhere.  I see them in the SQL statements as well, but these are being replaced by SQLAlchemy anyway.  Thanks for your input.

**Comment by rakhimov** [comment]
I am sure ``dos2unix`` got them (Windows CR) all in python files.
This PR doesn't clean anything but Python (just to deal with pylint),
so it should be safe to close. I leave this up to you.

I now noticed that there's a convention to put author/copyright info in code.
I don't know which convention is better.

**Pull request closed without merging**
